require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - db/**/**
    - bin/**
    - Guardfile
    - vendor/**/*
    - tmp/**/**
    - client/**/**
  SuggestExtensions: false

Style/SymbolProc:
  Exclude:
    - app/blueprints/**
    - spec/factories/**/**

Naming/FileName:
  Exclude:
    - config/initializers/**

Metrics/BlockLength:
  Exclude:
    - spec/**/**
    - lib/tasks/**
    - config/initializers/**
    - config/environments/**
    - config/routes.rb
    - app/blueprints/**

Metrics/ModuleLength:
  Exclude:
    - spec/**/**

# screens are bigger now and long lines are more acceptable
Layout/LineLength:
  Max: 180
  IgnoredPatterns: ['\A#']

# pending auto-enable
Lint/RaiseException:
  Enabled: true

# pending auto-enable
Lint/StructNewOverride:
  Enabled: true

Rails:
  Enabled: true

Style/Encoding:
  Enabled: false

# pending auto-enable
Style/HashEachMethods:
  Enabled: true

# pending auto-enable
Style/HashTransformKeys:
  Enabled: true

# pending auto-enable
Style/HashTransformValues:
  Enabled: true
