require: 
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
    - db/**/**
    - bin/**
    - Guardfile
    - vendor/**/*
    - tmp/**/**
    - client/**/**

Naming/FileName:
  Exclude:
    - config/initializers/**

Metrics/BlockLength:
  Exclude:
    - spec/**/**
    - lib/tasks/**
    - config/initializers/**
    - config/environments/**

# screens are bigger now and long lines are more acceptable
Layout/LineLength:
  Max: 180

# pending auto-enable
Lint/RaiseException:
  Enabled: true

# pending auto-enable
Lint/StructNewOverride:
  Enabled: true

Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - config/application.rb

Style/Encoding:
  Enabled: false

# pending auto-enable
Style/HashEachMethods:
  Enabled: true

# pending auto-enable
Style/HashTransformKeys:
  Enabled: true

# pending auto-enable
Style/HashTransformValues:
  Enabled: true