inherit_from: .rubocop_todo.yml

require:
  # - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - db/**/**
    - bin/**
    - Guardfile
    - vendor/**/*
    - tmp/**/**
    - client/**/**
  SuggestExtensions: false

Metrics/BlockLength:
  CountAsOne: ['array', 'heredoc', 'hash']

Metrics/ClassLength:
  CountAsOne: ['array', 'heredoc', 'hash']

Metrics/MethodLength:
  CountAsOne: ['array', 'heredoc', 'hash']

Metrics/ModuleLength:
  CountAsOne: ['array', 'heredoc', 'hash']

Layout/LineLength:
  Exclude:
    - config/routes.rb

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

# This doesn't get called in Rspec, only in minitest
Rails/RedundantTravelBack:
  Enabled: false

# Our earned revenue test needs a lot of helpers
RSpec/MultipleMemoizedHelpers:
  Enabled: false

# Turn off autocorrect on focused specs
RSpec/Focus:
  AutoCorrect: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - profile