#!/bin/bash
set -e

# This script builds the Docker container, seeds the app with sample data, starts the server, runs the tests, and logs the screen output.

DATE=`date +%Y%m%d-%H%M%S-%3N`
mkdir log/$DATE
docker/build-log 2>&1 | tee log/$DATE/build.log
wait
docker/test-log 2>&1 | tee log/$DATE/test.log
wait
docker/seed 2>&1 | tee log/$DATE/seed.log
wait
# docker/outline 2>&1 | tee log/$DATE/outline.log
# wait
docker/test_code 2>&1 | tee log/$DATE/test_code.log
wait
echo '******************************'
echo 'The build process is complete!'
echo ''
echo "The logs are in the log/$DATE directory."
echo ''
echo 'If all went well, the local app has been seeded, block diagrams are available,'
echo 'and all the tests passed.'
echo ''
echo 'Use the docker/server script to start up the app server.'
