#!/bin/bash
set -e

echo '----------------------------------'
echo 'BEGIN: bundle exec rake db:migrate'
echo '----------------------------------'
docker/run bundle exec rake db:migrate
echo '--------------------------------'
echo 'END: bundle exec rake db:migrate'
echo '--------------------------------'
