#!/bin/bash

echo '--------------------------'
echo 'rm -f /tmp/pids/server.pid'
rm -f /tmp/pids/server.pid

echo '-------------------'
echo 'docker-compose down'
docker-compose down

docker/bundle_install
docker/migrate

echo '--------------------------------------'
echo 'View this app at http://localhost:3000'
echo 'and the MailCatcher interface at http://localhost:1080'
echo ''
docker-compose up web
