#!/bin/bash
set -e

docker/bundle_install

echo '----------------------------'
echo 'BEGIN: yarn test-once (root)'
echo '----------------------------'
docker/run yarn test-once
echo '--------------------------'
echo 'END: yarn test-once (root)'
echo '--------------------------'

docker/run client/bin/test

docker/migrate

echo '------------------------'
echo 'BEGIN: bundle exec rspec'
echo '------------------------'
docker/run bundle exec rspec
echo '----------------------'
echo 'END: bundle exec rspec'
echo '----------------------'

echo '------------------------------'
echo 'BEGIN: bundle exec rails rswag'
echo '------------------------------'
docker/run bundle exec rails rswag
echo '----------------------------'
echo 'END: bundle exec rails rswag'
echo '----------------------------'
