#!/bin/bash

# Use this script for upgrading gems.

# If the version of a gem is pinned in the Gemfile, you must update
# the version number specified in that file.

# Do NOT use this script until you have set up this project with the docker/build script.

echo '-------------'
echo 'bundle update'
docker/run bundle update

docker/git_check
