%% TODO: Attributes and Methods
classDiagram
  class Attendance
  class Business
  class Case
  class Child
  class ChildCasePeriod
  class ServiceDay
  class User {
    +Uuid id
    +Boolean active
    +Boolean admin
    +DateTime confirmation_sent_at
    +String confirmation_token
    +DateTime confirmed_at
    +DateTime current_sign_in_at
    +INet current_sign_in_ip
    +DateTime deleted_at
    +String email
    +String encrypted_password
    +String full_name
    +String greeting_name
    +String language
    +DateTime last_sign_in_at
    +INet last_sign_in_ip
    +Boolean opt_in_email
    +Boolean opt_in_text
    +String organization
    +String phone_number
    +String phone_type
    +DateTime remember_created_at
    +DateTime reset_password_sent_at
    +String reset_password_token
    +Boolean service_agreement_accepted
    +Integer sign_in_count
    +String timezone
    +String unconfirmed_email
    +DateTime created_at
    +DateTime updated_at
  }
  User "1" *-- "*" Business
  Business "1" *-- "*" Case
  Case "1" *-- "1..*" ChildCasePeriod
  Case "1" *-- "1..*" Child
  ChildCasePeriod "1..*" --* "1" Child
  Child "1" o-- "*" ServiceDay
  ServiceDay "1" o-- "1..*" Attendance
  class State
  class StateDurationRule
  class StateAbsenceLimit
  class StateEarnedRevenueCalculator
  class StateRate
  class StateRateConfiguration
  State "1" *-- "*" StateDurationRule
  State "1" *-- "*" StateAbsenceLimit
  State "1" *-- "*" StateEarnedRevenueCalculator
  State "1" *-- "*" StateRate
  State "1" *-- "*" StateRateConfiguration