sequenceDiagram
    %% User loops children to request earned revenue for each
    User->>+Child: children
    loop children
      Child-->>User: Child
      %% User requests earned_revenue for each child
      User->>+EarnedRevenueCalculator: earned_revenue(Child, date)
      
      %% EarnedRevenueCalculator determines the right [Nebraska]EarnedRevenueCalculator
      %% based on the User's state, then requests earned_revenue for each child
      EarnedRevenueCalculator->>+NebraskaEarnedRevenueCalculator: call(Child, date)

      NebraskaEarnedRevenueCalculator->>+ServiceDay: service_days_this_month(Child, date)
      loop service_days
        ServiceDay->>+Attendance: attendances(self)
        Attendance-->>ServiceDay: time_in_care, absence
        ServiceDay->>+ServiceDay: total_time_in_care
        ServiceDay->>+ServiceDay: duration_type
        ServiceDay->>+ServiceDay: absence?
        ServiceDay->>+NebraskaRate: rate(self)
        %% NebraskaRate.where(region:).where(max_age:).where(enrolled_in_school:).where(accredited:).where(qris_rating:).(license_type:).where(duration:)
        NebraskaRate-->>ServiceDay: rate
        ServiceDay-->>NebraskaEarnedRevenueCalculator: [ServiceDay(total_time_in_care, absence, rate, duration_type)]
      end
      %% Are there any absences in the service_days list?
      NebraskaEarnedRevenueCalculator->>+NebraskaEarnedRevenueCalculator: absences?(service_days_this_month)
      alt Absences Present
          NebraskaEarnedRevenueCalculator->>+Nebraska/ServiceDayLimiter: call(date, Nebraska::Absence, service_days_this_month)
          Nebraska/ServiceDayLimiter-->>NebraskaEarnedRevenueCalculator: remaining_service_days
      end
      %% Are there any hourly durations in the service_days list?
      NebraskaEarnedRevenueCalculator->>+NebraskaEarnedRevenueCalculator: hourly?(service_days_this_month)
      alt Hourly DurationType
          NebraskaEarnedRevenueCalculator->>+Nebraska/ServiceDayLimiter: call(date, Nebraska::Hourly, service_days_this_month)
          Nebraska/ServiceDayLimiter-->>NebraskaEarnedRevenueCalculator: remaining_service_days
      end
      %% Are there any daily durations in the service_days list?
      NebraskaEarnedRevenueCalculator->>+NebraskaEarnedRevenueCalculator: daily?(service_days_this_month)
      alt Daily DurationType
          NebraskaEarnedRevenueCalculator->>+Nebraska/ServiceDayLimiter: call(date, Nebraska::Daily, service_days_this_month)
          Nebraska/ServiceDayLimiter-->>NebraskaEarnedRevenueCalculator: remaining_service_days
      end
      NebraskaEarnedRevenueCalculator-->>EarnedRevenueCalculator: earned_revenue
      EarnedRevenueCalculator-->>User: earned_revenue
    end