// This is the source file for generating ER diagrams on
// https://dbdiagram.io/d/5f552f2e88d052352cb625e2
Table users {
  id uuid [pk, unique, not null]
  full_name string [not null]
  greeting_name string
  email string [unique, not null]
  phone_number string
  phone_type string
  opt_in_text boolean [not null, default: true]
  opt_in_email boolean [not null, default: true]
  organization string [not null]
  password string [not null] // devise
  active boolean [not null, default: true]
  language string [not null]
  confirmed boolean [not null, default: false] // devise
  service_agreement_accepted boolean [not null, default: false]
  timezone string [not null]
}

Enum license_types {
  licensed_center
  licensed_family_home
  licensed_group_home
  license_exempt_home
  license_exempt_center
}

Table businesses {
  id uuid [pk, unique, not null]
  user_id uuid [ref: > users.id, not null]
  license_type license_types [not null]
  name string [not null]
  active boolean [not null, default: true]
  qris_rating string
  zip_id uuid [not null]
  county_id uuid [not null]
}

Table children {
  id uuid [pk, unique, not null]
  user_id uuid [ref: > users.id, not null]
  full_name string [not null]
  date_of_birth date [not null]
  active boolean [not null, default: true]
}

Enum copay_frequencies {
  daily
  weekly
  monthly
}

Table case_cycles {
  id uuid [pk, unique, not null]
  user_id uuid [ref: > users.id, not null]
  case_number string
  copay monetize
  copay_frequency copay_frequencies
  effective_on date
  expires_on date
}

Enum allowance_intervals {
  weekly
  monthly
  annually
}

Table child_case_cycles {
  id uuid [pk, unique, not null]
  child_id uuid [ref: > children.id, not null]
  subsidy_rule_id uuid [ref: > subsidy_rules.id, not null]
  case_cycle_id uuid [ref: > case_cycles.id, not null]
  part_days_allowed integer [not null]
  full_days_allowed integer [not null]
}

Enum duration_definitions {
  part_day
  full_day
  full_plus_part_day
  full_plus_full_day
}

Table attendances {
  id uuid [pk, unique, not null]
  child_case_cycle_id uuid [ref: > child_case_cycles.id, not null]
  starts_on date [not null]
  check_in time [not null]
  check_out time [not null]
  total_time_in_care duration [not null]
  attendance_duration duration_definitions [not null]
}

Table subsidy_rules {
  id uuid [pk, unique, not null]
  name string [not null]
  county_id  uuid
  state_id  uuid
  max_age decimal [not null]
  hourly_rate monetize
  max_subsidy_hours decimal
  part_day_rate monetize
  full_day_rate monetize
  part_day_max_hours decimal
  full_day_max_hours decimal
  full_plus_part_day_max_hours decimal
  full_plus_full_day_max_hours decimal
  part_day_threshold decimal
  full_day_threshold decimal
  license_type license_types [not null]
  qris_rating string
}


Table lookup_cities {
  id uuid [not null, default: `gen_random_uuid()`]
  name varchar [not null]
  state_id uuid [not null]
  county_id uuid
}

Table lookup_counties {
  id uuid [not null, default: `gen_random_uuid()`]
  state_id uuid
  abbr varchar
  name varchar [not null]
  county_seat varchar
}

Table lookup_states {
  id uuid [not null, default: `gen_random_uuid()`]
  abbr varchar(2) [not null]
  name varchar [not null]
}

Table lookup_zipcodes {
  id uuid [not null, default: `gen_random_uuid()`]
  code varchar [not null]
  state_id uuid
  county_id uuid
  city_id uuid
  area_code varchar
  lat numeric(15, 10)
  lon numeric(15, 10)
}
