name: E2E CI
concurrency: 
  group: e2e-${{ github.head_ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - 'main'
  pull_request:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:
jobs:
  e2e_tests:
    name: E2E tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.2
      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev
      - name: Bundle install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Set up database
        run: |
          cp config/database.yml.github-actions config/database.yml
          bundle exec rake db:create
          bundle exec rake db:schema:load
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          DEVISE_JWT_SECRET_KEY: imasecretkey
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: '16'
      - name: Run Cypress tests
        run: yarn cy:ci
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          DEVISE_JWT_SECRET_KEY: imasecretkey
